### PR TITLE
Optimize and cleanup explosion events from entities

### LINKED ISSUE #2099: Denying ghast-fireball prevents wind charges from working
### WorldEdit Version

WorldEdit 7.3.4 Beta 1

### WorldGuard Version

7.0.11-beta1

### Platform Version

Paper 1.21 Build 40

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Setting the `ghast-fireball` flag to `Deny` in a region causes this region to also block wind charges.

### Expected Behavior

Wind charges should not be affected by the `ghast-fireball` flag.

### Reproduction Steps

1. Set the `ghast-fireball` flag to `Deny`
2. Attempt to use a wind charge
This issue also occurs with Breezes

### Optional WorldGuard-Report

_No response_

### Anything Else?

I suspect this issue occurs because `AbstractWindCharge` extends the `Fireball` interface, which is being used by WorldGuard to detect Ghast fireball explosions in the `onEntityExplode` method of the `WorldGuardEntityListener`.

### PR DESCRIPTION
**Pull request by Joo200**
This PR is the start of a cleanup of explosion handling in WorldGuard.

Currently this draft has some ToDos:

- [x] Hitting players with the wind charge are not protected by the EntityDamageByEntityEvent. (requires Paper Debug session)
- [ ] I moved the flag handling for explosion block damage to EventAbstractionListener. Validate this is not breaking.

Fixes #2099 and #2097

### CODE REVIEW

**Comment by Joo200** [comment]
Waiting on response for this issue: https://github.com/PaperMC/Paper/issues/7168#issuecomment-2254170659

File: worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/WorldGuardEntityListener.java [hunk 1]
```diff
@@ -592,6 +572,11 @@ public void onExplosionPrime(ExplosionPrimeEvent event) {
                 event.setCancelled(true);
                 return;
             }
+        } else if (event instanceof AbstractWindCharge) {
```
Comment (mcmonkey4eva) [inline worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/WorldGuardEntityListener.java:575]: This appears to be a typo^ `event` where you meant `event.getEntity()`
(Thanks to hyper in the Denizen discord who happened to look at this while investigating something else)
