### PR TITLE
Fix NPE when non-player entities create new nether portals

### LINKED ISSUE #1993: When non-player entities create new nether portals, an error occurs
### WorldEdit Version

7.2.15-SNAPSHOT

### WorldGuard Version

7.1.0-SNAPSHOT

### Platform Version

git-Paper-478 (MC: 1.19.4)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When a non-player entity, like a Pig, initiates nether portal creation WorldGuard has an internal error:
```
[18:13:31 ERROR]: Could not pass event PortalCreateEvent to WorldGuard v7.1.0-SNAPSHOT+2232-b67fd01
java.lang.NullPointerException: The build flag is handled in a special fashion and requires a non-null subject parameter
        at com.sk89q.worldguard.protection.FlagValueCalculator.queryAllValues(FlagValueCalculator.java:392) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldguard.protection.FlagValueCalculator.queryValue(FlagValueCalculator.java:227) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldguard.protection.FlagValueCalculator.queryState(FlagValueCalculator.java:174) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldguard.protection.RegionResultSet.queryState(RegionResultSet.java:103) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldguard.protection.AbstractRegionSet.testState(AbstractRegionSet.java:34) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardEntityListener.onCreatePortal(WorldGuardEntityListener.java:679) ~[worldguard-bukkit-7.1.0-SNAPSHOT-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor137.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1952]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.portal.PortalForcer.createPortal(PortalForcer.java:224) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mpldefgen377ba225.createNetherPortal(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mpldefgen377ba225.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.logic.PortalHandler_1_14_1$PortalTravelAgentHandle$impl.createNetherPortal(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.logic.PortalHandler_1_14_1.createNetherPortal(PortalHandler_1_14_1.java:87) ~[BKCommonLib-1.19.4-v1-SNAPSHOT-NO-CI.jar:?]
        at com.bergerkiller.bukkit.common.utils.WorldUtil.createNetherPortal(WorldUtil.java:559) ~[BKCommonLib-1.19.4-v1-SNAPSHOT-NO-CI.jar:?]
        at com.bergerkiller.bukkit.mw.portal.NetherPortalSearcher$SearchResult.whenLoaded(NetherPortalSearcher.java:311) ~[MyWorlds-1.19.4-v1-SNAPSHOT-NO-CI.jar:?]
        at com.bergerkiller.bukkit.mw.portal.NetherPortalSearcher$SearchResult.lambda$verify$2(NetherPortalSearcher.java:289) ~[MyWorlds-1.19.4-v1-SNAPSHOT-NO-CI.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.CommonForcedChunkManager$Entry.lambda$accept$0(CommonForcedChunkManager.java:365) ~[BKCommonLib-1.19.4-v1-SNAPSHOT-NO-CI.jar:?]
        at com.bergerkiller.bukkit.common.internal.CommonNextTickExecutor$ExecutorTask.run(CommonNextTickExecutor.java:161) ~[BKCommonLib-1.19.4-v1-SNAPSHOT-NO-CI.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

This is because the Entity initiating it isnt a player, so the **associable** here is null:
https://github.com/EngineHub/WorldGuard/blob/master/worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/WorldGuardEntityListener.java#L679

The methods claim they support a nullable associable, but I guess its querying a flag that requires one. It probably need a null check at that location. Besides printing that error, there appears to not be any other problem.

### Expected Behavior

No error

### Reproduction Steps

1. Install worldedit and worldguard
2. Add MyWorlds and BKCommonLib (unsure if this is critical, but its myworlds thats firing a portal create event through NMS code with the pig or other non-player entity as initiator)
3. Create a new nether portal on one world
4. Spawn a pig and make it enter it, so it creates a fresh portal on the other end

### Optional WorldGuard-Report

_No response_

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by stonar96**
Resolves #1993. <strike>I didn't test this yet (will do later).</strike> Note that the (root) causing entity might be in a different world than the created portal, which means that the action will be blocked in a protected region by default (provided that Vanilla even allows this, which isn't the case currently).

### CODE REVIEW

File: worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/WorldGuardEntityListener.java [hunk 1]
```diff
@@ -653,35 +657,46 @@ public void onCreatureSpawn(CreatureSpawnEvent event) {
...
-            }
-            ProtectedCuboidRegion target = new ProtectedCuboidRegion("__portal_check", true, min, max);
-            final ApplicableRegionSet regions = regionManager.getApplicableRegions(target);
-            if (!regions.testState(associable, Flags.BUILD, Flags.BLOCK_PLACE)) {
-                if (associable != null) {
+            final RegionManager regionManager = WorldGuard.getInstance().getPlatform().getRegionContainer()
+                    .get(world);
+            ApplicableRegionSet regions;
+            if (regionManager == null) {
+                regions = FailedLoadRegionSet.getInstance();
```
Comment (wizjany) [inline worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/WorldGuardEntityListener.java:679]: isn't regionmanager also null if use-regions is false? in which case this should be the permissive set. really feels like we should delegate this to regionquery since it has this logic already.

Comment (stonar96) [reply worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/WorldGuardEntityListener.java:679]: I've handled that case above already.

File: worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/WorldGuardEntityListener.java [hunk 2]
```diff
@@ -653,35 +657,46 @@ public void onCreatureSpawn(CreatureSpawnEvent event) {
...
+                    min = min == null ? loc : loc.getMinimum(min);
+                    max = max == null ? loc : loc.getMaximum(max);
+                }
+                ProtectedCuboidRegion target = new ProtectedCuboidRegion("__portal_check", true, min, max);
+                regions = regionManager.getApplicableRegions(target);
+            }
+            final RegionAssociable associable = createRegionAssociable(cause);
+            final State buildState = StateFlag.denyToNone(regions.queryState(associable, Flags.BUILD));
+            if (!StateFlag.test(buildState, regions.queryState(associable, Flags.BLOCK_BREAK))
+                    || !StateFlag.test(buildState, regions.queryState(associable, Flags.BLOCK_PLACE))) {
```
[the remark this answers is not in the document]
Comment (stonar96) [reply worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/WorldGuardEntityListener.java:694]: Yeah, that method should be in ARS.

File: worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/WorldGuardEntityListener.java (hunk 1 above)
Comment (stonar96) [reply worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/WorldGuardEntityListener.java:679]: > really feels like we should delegate this to regionquery since it has this logic already.

I'm not exactly sure what you mean by "delegate this" here. RQ isn't used here because we don't query regions at a specific location but for the whole portal region. Should I add a method to RQ for that too?
